trigger:
  branches:
    include:
    - vnext
    - master

# This pipeline is meant to build specific branches for deployment. It's not meant to be a part of PR validation.
pr: none

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false
- name: shouldCleanPostExecution
  displayName: 'Clean all pipeline dirs after the pipeline finishes?'
  type: boolean
  default: true

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
- stage: Build
  pool:
    vmImage: 'windows-latest'

  jobs:
  - job: BuildSamples
    steps:
      - checkout: 'self' 
        clean: true

      - task: NodeTool@0
        displayName: 'Install Node'
        inputs:
          versionSource: 'spec'
          versionSpec: '18.x'

      - task: Npm@1
        displayName: 'npm install --legacy-peer-deps'
        inputs:
          verbose: ${{ parameters.isVerbose }}
          command: custom
          workingDir: '$(Build.SourcesDirectory)'
          customCommand: 'install --legacy-peer-deps'

      - task: Npm@1
        displayName: 'Install @angular/cli globally'
        inputs:
          verbose: ${{ parameters.isVerbose }}
          command: custom
          workingDir: '$(Build.SourcesDirectory)'
          customCommand: 'install -g @angular/cli'


      - task: Npm@1
        displayName: 'Register licensed npm registry in .npmrc'
        inputs:
          verbose: ${{ parameters.isVerbose }}
          command: 'custom'
          workingDir: '$(Build.SourcesDirectory)'
          customCommand: 'config -L project set @infragistics:registry=https://packages.infragistics.com/npm/js-licensed/'

      - task: npmAuthenticate@0
        displayName: '[IG Production ProGet] npm authenticate'
        inputs:
          workingFile: '$(Build.SourcesDirectory)\.npmrc'
          customEndpoint: 'public proget'

      - task: PowerShell@2
        displayName: 'Run Angular Schematics Upgrade Packages'
        inputs:
          targetType: 'inline'
          script: |
            npx --userconfig=$(Build.SourcesDirectory)\.npmrc --legacy-peer-deps ng g @igniteui/angular-schematics:upgrade-packages

      - task: Npm@1
        displayName: 'npm run build:ci'
        inputs:
          command: custom
          workingDir: '$(Build.SourcesDirectory)'
          verbose: ${{ parameters.isVerbose }}
          customCommand: 'run build:ci'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish pipeline artifact'
        inputs:
          targetPath: '$(Build.SourcesDirectory)\dist\grid-demos\browser'
          artifact: 'dist.grid-demos.browser'
          publishLocation: 'pipeline'

      - task: PowerShell@2
        displayName: 'Create download artifact per sample'
        inputs:
          targetType: 'inline'
          script: |
            $rootPath = "$(Build.SourcesDirectory)\projects"
            
            # Get all first-level subdirectories in the specified root path
            $subdirectories = Get-ChildItem -Path $rootPath -Directory
            
            $textInfo = [System.Globalization.CultureInfo]::CurrentCulture.TextInfo
            
            foreach ($subdirectory in $subdirectories) {
                # Get the current directory name
                $dirName = $subdirectory.Name
                #Write-Output $dirName
            
                # Check if the directory name is already in camel-case
                if ($dirName -cmatch '^[A-Z]+[a-z]+(?:[A-Z][a-z]*)*$') {
                    # If already camel-case, print it as is
                    Write-Output $dirName
                }
                else {
                    Write-Output $textInfo.ToTitleCase($dirName).replace("-","")
                }
            }
            /*
              How to compress the zip files:
                $compress = @{
                LiteralPath= "/mnt/d/Work/git/grid-demos/projects/finance-grid"
                DestinationPath = "/mnt/d/Work/git/grid-demos/projects/finance-grid.zip"
                }
                Compress-Archive @compress
            */

            # TODO - we want each sample's zip to be named IgniteUI_Angular_ApplicationSample_<sample name>_Source.zip
          failOnStderr: true
          pwsh: true

      - ${{ if eq(parameters.shouldCleanPostExecution, true) }}:
        - task: PostBuildCleanup@4
